
import './globals.css'
import Layout from "./components/layout/layout";

export const metadata = {
  title: 'Depot',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-white">
   
            <Layout>
                {children}
              </Layout>
   
   
       
      </body>
    </html>
  )
} 